language: node_js
sudo: false
node_js:
- '6.0.0'
- node
- lts/*
before_install:
- "export CHROME_BIN=chromium-browser"
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
before_deploy:
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
deploy:
  - provider: releases
    api_key:
      secure: "MLMEXZvtp5LVsVrwDbpX992YFT8DpOKgWILsVZjo/S2GXxWBzouYLzxIrDgIHuplj/J18+9psgntuLgcXu/ffrUh167M6c0mwVSlvJySbJwJm/3Vl+i5IiDII5rXgG0QkNtHpYbR+O8YLzFl4+wtE25TDDWpQMvimc2rOrthz4c="
    file:
      - dist/mp4box.all.js
      - dist/mp4box.all.min.js
      - dist/mp4box.all.min.js.map
      - dist/mp4box.simple.js
      - dist/mp4box.simple.min.js
      - dist/mp4box.simple.min.js.map
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: cyril.concolato@telecom-paristech.fr
    api_key:
      secure: qT37keNDM4h+9o7XvnCKDF/Hxt+zAcUtaqI78EHu77J22tWKFW45MJw8iL6yyJCit7kRyYAd/YSgk1LwwdJQwlWmuDIYYiF27NfGeLD+md1OlaPztUNhO9h6mm1jjSSYhhMEf3p2ugNmFih2EkXvodYcvhEpJyAMAeSU4jdmtGk=
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master
